// ---------------------------------------------------------------------------
// `jarvis`, typed into any terminal.
//
// Installing an app puts it in the Start menu. It does not give you a command.
// So the gap this closes is the one a user actually hits: they install Jarvis,
// open a terminal, type `jarvis`, and get "not recognized".
//
// WHAT IT DOES
//   1. Writes a tiny launcher into a stable per-user directory
//        Windows  %LOCALAPPDATA%\Jarvis\bin\jarvis.cmd
//        macOS/Linux  ~/.local/bin/jarvis
//   2. Puts that directory on PATH, persistently, for this user only.
//
// WHAT IT REFUSES TO DO, and why:
//
//   * NO `setx`. It truncates PATH at 1024 characters and rewrites REG_EXPAND_SZ
//     as REG_SZ, so `%JAVA_HOME%\bin` stops expanding. It is the single most
//     common way a tool destroys someone's PATH. The registry is written
//     directly instead, preserving the original value KIND.
//   * NO machine-wide change and NO elevation. HKCU only. A command prompt for
//     Administrator that the user did not ask for is not an install step.
//   * NO second `jarvis`. If one is already on PATH — `npm i -g` puts one there
//     — that one is left alone and reported. Two shims for the same name is a
//     bug that only shows up months later when they disagree.
//   * NO claim of success from an exit code. The registry value is read back
//     after writing, and the previous value is saved to disk first.
//
// The current shell CANNOT see the change: a process inherits its environment
// at spawn time. Every code path here says "open a new terminal" rather than
// pretending otherwise. WM_SETTINGCHANGE is broadcast so Explorer and any shell
// started afterwards pick it up without a logout.
// ---------------------------------------------------------------------------

const os = require('node:os');
const fs = require('node:fs');
const fsp = require('node:fs/promises');
const path = require('node:path');
const { execFile } = require('node:child_process');

const detect = require('./detect.js');

/** Marks the block this tool owns in a shell rc file, for update and removal. */
const RC_MARKER = 'JARVIS_PATH_BLOCK';
/* ASCII only, deliberately. cmd.exe reads a .cmd file in the console's OEM
   codepage, so a UTF-8 em dash in this comment renders as mojibake in a file
   the user is invited to open and read. */
const GENERATED = 'generated by `jarvis setup` - safe to delete';

// ── where things go ─────────────────────────────────────────────────────────

/**
 * The directory the launcher is written to.
 *
 * Deliberately NOT the install directory. On Windows an app can be installed
 * per-user or per-machine, into Program Files or anywhere the user chose, and
 * on macOS it lives inside a .app bundle. Putting a stable directory on PATH
 * and a launcher inside it means the app can move, update or be reinstalled
 * without the PATH entry ever having to change again.
 */
function commandDir(platform = detect.platform().os, env = process.env, home = os.homedir()) {
    if (platform === 'windows') {
        return path.join(env.LOCALAPPDATA || path.join(home, 'AppData', 'Local'), 'Jarvis', 'bin');
    }
    // ~/.local/bin is the XDG-blessed location and is already on PATH on most
    // modern distributions and on macOS with Homebrew's profile — which means
    // the common case needs no rc file edit at all.
    return path.join(home, '.local', 'bin');
}

function commandName(platform = detect.platform().os) {
    return platform === 'windows' ? 'jarvis.cmd' : 'jarvis';
}

function commandPath(platform = detect.platform().os) {
    return path.join(commandDir(platform), commandName(platform));
}

// ── what the launcher runs ──────────────────────────────────────────────────

/**
 * Decide what the shim should invoke.
 *
 * Two shapes, and they behave differently on purpose:
 *
 *   'cli'  installed from npm or run from a clone. `node bin/jarvis.mjs` —
 *          the full command line: doctor, setup, repair, --version.
 *   'app'  installed from the packaged build. There is no Node and no
 *          bin/jarvis.mjs on disk (it is inside app.asar), so the shim runs the
 *          executable. That LAUNCHES Jarvis; the subcommands are not available
 *          from a GUI binary, and this is stated rather than half-supported.
 *
 * @param {object} o
 * @param {string} o.root install directory
 * @param {string|null} [o.packagedExe] the app executable, when packaged
 * @param {string} [o.execPath] this process's binary
 */
function resolveLauncher({ root, packagedExe = null, execPath = process.execPath,
    platform = detect.platform().os } = {}) {
    if (packagedExe) {
        return {
            kind: 'app',
            cmd: packagedExe,
            args: [],
            // A GUI app started from cmd.exe would otherwise hold the terminal
            // until the window closes.
            detach: platform === 'windows',
        };
    }

    const script = path.join(root, 'bin', 'jarvis.mjs');
    const base = path.basename(execPath || '').toLowerCase();
    // Inside Electron, execPath is the Electron binary and running a .mjs with
    // it does nothing useful. Only an actual node binary is used as an absolute
    // path; otherwise fall back to whatever `node` is on PATH at run time.
    const node = /^node(\.exe)?$/.test(base) ? execPath : 'node';

    return { kind: 'cli', cmd: node, args: [script], detach: false };
}

/**
 * The launcher script itself. PURE — the whole point is that the exact bytes
 * that will be written can be asserted in a test on any platform.
 */
function shimContents({ platform, cmd, args = [], detach = false }) {
    if (platform === 'windows') {
        const quoted = [cmd, ...args].map((a) => `"${a}"`).join(' ');
        // `start ""` needs the empty title argument: without it, a quoted path
        // is consumed AS the window title and nothing launches.
        const line = detach ? `start "" ${quoted} %*` : `${quoted} %*`;
        return [
            '@echo off',
            `rem ${GENERATED}`,
            'setlocal',
            line,
            '',
        ].join('\r\n');
    }

    const quoted = [cmd, ...args].map((a) => `"${a.replace(/"/g, '\\"')}"`).join(' ');
    return [
        '#!/bin/sh',
        `# ${GENERATED}`,
        // exec, so signals and the exit code belong to Jarvis rather than to a
        // shell wrapper that outlives it.
        `exec ${quoted} "$@"`,
        '',
    ].join('\n');
}

// ── PATH arithmetic (pure) ──────────────────────────────────────────────────

const SEP = (platform) => (platform === 'windows' ? ';' : ':');

function splitPath(value, platform) {
    return String(value || '').split(SEP(platform)).filter((s) => s !== '');
}

/** Trailing separators and case are not meaningful on Windows; here they are. */
function samePathEntry(a, b, platform) {
    const norm = (s) => {
        const trimmed = String(s).replace(/[\\/]+$/, '');
        return platform === 'windows' ? trimmed.toLowerCase().replace(/\//g, '\\') : trimmed;
    };
    return norm(a) === norm(b);
}

function pathContains(value, dir, platform) {
    return splitPath(value, platform).some((entry) => samePathEntry(entry, dir, platform));
}

/**
 * PATH with `dir` appended, or unchanged if it is already there.
 * Appended, not prepended: this directory must never shadow a command the user
 * installed deliberately.
 */
function pathWith(value, dir, platform) {
    if (pathContains(value, dir, platform)) return { value: String(value || ''), changed: false };
    const trimmed = String(value || '').replace(new RegExp(`${SEP(platform)}+$`), '');
    return {
        value: trimmed === '' ? dir : trimmed + SEP(platform) + dir,
        changed: true,
    };
}

function pathWithout(value, dir, platform) {
    const kept = splitPath(value, platform).filter((entry) => !samePathEntry(entry, dir, platform));
    const next = kept.join(SEP(platform));
    return { value: next, changed: next !== String(value || '') };
}

// ── shell rc blocks (pure) ──────────────────────────────────────────────────

function rcBlock(dir) {
    // POSIX sh, not bash — this is sourced by dash on Debian's /bin/sh.
    // The guard means a doubled rc entry cannot double the PATH entry.
    return [
        ``,
        `# ${RC_MARKER} — ${GENERATED}`,
        `case ":$PATH:" in`,
        `  *":${dir}:"*) ;;`,
        `  *) PATH="$PATH:${dir}" ;;`,
        `esac`,
        `export PATH`,
        `# end ${RC_MARKER}`,
        ``,
    ].join('\n');
}

function rcHasBlock(text) {
    return String(text || '').includes(RC_MARKER);
}

/** Remove a previously written block, leaving everything else byte-identical. */
function rcWithoutBlock(text) {
    const lines = String(text || '').split('\n');
    const out = [];
    let inside = false;
    for (const line of lines) {
        if (!inside && line.includes(`# ${RC_MARKER} —`)) { inside = true; continue; }
        if (inside) {
            if (line.includes(`# end ${RC_MARKER}`)) inside = false;
            continue;
        }
        out.push(line);
    }
    return out.join('\n');
}

/** rc files worth editing, in the order a login shell reads them. */
function rcCandidates(home = os.homedir(), env = process.env) {
    const shell = String(env.SHELL || '');
    const files = [];
    if (/zsh/.test(shell)) files.push(path.join(home, '.zshrc'));
    if (/bash/.test(shell)) files.push(path.join(home, '.bashrc'));
    // Whatever the login shell is, these are read by the others too. Existing
    // files only — creating a .zshrc on a bash machine is litter.
    for (const name of ['.zshrc', '.bashrc', '.profile']) {
        const p = path.join(home, name);
        if (!files.includes(p)) files.push(p);
    }
    return files;
}

// ── Windows registry ────────────────────────────────────────────────────────

function runPowerShell(script, env = {}) {
    return new Promise((resolve) => {
        execFile('powershell', [
            '-NoProfile', '-NonInteractive', '-ExecutionPolicy', 'Bypass', '-Command', script,
        ], {
            timeout: 25000,
            windowsHide: true,
            env: { ...process.env, ...env },
        }, (err, stdout, stderr) => {
            resolve({
                ok: !err,
                out: String(stdout || '').trim(),
                err: String(stderr || '').trim() || (err ? err.message : ''),
            });
        });
    });
}

/**
 * The user's PATH as STORED, not as expanded into this process.
 *
 * `process.env.PATH` is the merged machine+user value this process inherited,
 * which cannot answer "did our entry get persisted". `reg query` is used rather
 * than PowerShell because it is ~30 ms against ~700 ms of PowerShell startup,
 * and this runs on every launch.
 *
 * @returns {Promise<string|null>} null means "could not read", never "empty".
 */
async function persistedWindowsPath() {
    const out = await detect.run('reg', ['query', 'HKCU\\Environment', '/v', 'Path'], 6000);
    if (out === null) return null;
    const m = out.match(/^\s*Path\s+REG_(?:EXPAND_)?SZ\s+(.*)$/mi);
    return m ? m[1].trim() : null;
}

/** Shared by the add and remove scripts: make new shells see it without a logout. */
const PS_BROADCAST = `
$sig = '[DllImport("user32.dll", SetLastError=true, CharSet=CharSet.Auto)] public static extern IntPtr SendMessageTimeout(IntPtr hWnd, uint Msg, UIntPtr wParam, string lParam, uint fuFlags, uint uTimeout, out UIntPtr lpdwResult);'
try {
  Add-Type -MemberDefinition $sig -Name Env -Namespace Win32 -ErrorAction Stop | Out-Null
  $res = [UIntPtr]::Zero
  [Win32.Env]::SendMessageTimeout([IntPtr]0xffff, 0x1A, [UIntPtr]::Zero, 'Environment', 2, 3000, [ref]$res) | Out-Null
} catch { }
`;

/**
 * Add the directory to the user's PATH in the registry.
 *
 * The directory arrives through an environment variable, never interpolated
 * into the script text — a path with a quote or a `$` in it would otherwise be
 * script, and this script writes to the registry.
 */
async function addToWindowsPath(dir, backupFile) {
    const script = `
$ErrorActionPreference = 'Stop'
$dir = $env:JARVIS_PATH_DIR
if ([string]::IsNullOrWhiteSpace($dir)) { Write-Output 'ERROR:no-dir'; exit 1 }

$key = [Microsoft.Win32.Registry]::CurrentUser.OpenSubKey('Environment', $true)
if ($null -eq $key) { $key = [Microsoft.Win32.Registry]::CurrentUser.CreateSubKey('Environment') }

# Preserve the VALUE KIND. A REG_EXPAND_SZ rewritten as REG_SZ silently stops
# expanding every %VAR% already in the user's PATH.
$kind = [Microsoft.Win32.RegistryValueKind]::ExpandString
try { $kind = $key.GetValueKind('Path') } catch { }

$raw = $key.GetValue('Path', '', [Microsoft.Win32.RegistryValueOptions]::DoNotExpandEnvironmentNames)
if ($null -eq $raw) { $raw = '' }

if ($env:JARVIS_PATH_BACKUP) { [System.IO.File]::WriteAllText($env:JARVIS_PATH_BACKUP, $raw) }

$target = $dir.TrimEnd('\\')
$hit = @($raw -split ';' | Where-Object { $_ -ne '' } | Where-Object { $_.TrimEnd('\\') -ieq $target })
if ($hit.Count -gt 0) { Write-Output 'UNCHANGED'; exit 0 }

$trimmed = $raw.TrimEnd(';')
if ($trimmed -eq '') { $new = $dir } else { $new = $trimmed + ';' + $dir }
$key.SetValue('Path', $new, $kind)

# Read back. An exit code says the call returned, not that the value landed.
$check = $key.GetValue('Path', '', [Microsoft.Win32.RegistryValueOptions]::DoNotExpandEnvironmentNames)
if ($check -ne $new) { Write-Output 'ERROR:not-persisted'; exit 1 }
${PS_BROADCAST}
Write-Output 'UPDATED'
`;

    const res = await runPowerShell(script, {
        JARVIS_PATH_DIR: dir,
        JARVIS_PATH_BACKUP: backupFile || '',
    });

    if (res.out.includes('UNCHANGED')) return { changed: false, ok: true };
    if (res.out.includes('UPDATED')) return { changed: true, ok: true };
    return { changed: false, ok: false, detail: res.out || res.err || 'the registry write did not report back' };
}

async function removeFromWindowsPath(dir) {
    const script = `
$ErrorActionPreference = 'Stop'
$dir = $env:JARVIS_PATH_DIR
$key = [Microsoft.Win32.Registry]::CurrentUser.OpenSubKey('Environment', $true)
if ($null -eq $key) { Write-Output 'UNCHANGED'; exit 0 }
$kind = [Microsoft.Win32.RegistryValueKind]::ExpandString
try { $kind = $key.GetValueKind('Path') } catch { }
$raw = $key.GetValue('Path', '', [Microsoft.Win32.RegistryValueOptions]::DoNotExpandEnvironmentNames)
if ($null -eq $raw) { Write-Output 'UNCHANGED'; exit 0 }
$target = $dir.TrimEnd('\\')
$kept = @($raw -split ';' | Where-Object { $_ -ne '' } | Where-Object { $_.TrimEnd('\\') -ine $target })
$new = ($kept -join ';')
if ($new -eq $raw) { Write-Output 'UNCHANGED'; exit 0 }
$key.SetValue('Path', $new, $kind)
${PS_BROADCAST}
Write-Output 'UPDATED'
`;
    const res = await runPowerShell(script, { JARVIS_PATH_DIR: dir });
    if (res.out.includes('UNCHANGED')) return { changed: false, ok: true };
    if (res.out.includes('UPDATED')) return { changed: true, ok: true };
    return { changed: false, ok: false, detail: res.out || res.err };
}

// ── state ───────────────────────────────────────────────────────────────────

/**
 * Is the launcher directory actually registered for future shells?
 *
 * Separate from "is `jarvis` on PATH right now", because immediately after
 * installing it the answer to the second question is NO in this process and
 * YES in the next terminal. Reporting failure there would be wrong.
 */
async function dirIsRegistered(dir = commandDir(), platform = detect.platform().os) {
    if (platform === 'windows') {
        const stored = await persistedWindowsPath();
        if (stored === null) return false;
        return pathContains(stored, dir, platform);
    }
    if (pathContains(process.env.PATH, dir, platform)) return true;
    for (const file of rcCandidates()) {
        try {
            if (rcHasBlock(fs.readFileSync(file, 'utf-8'))) return true;
        } catch { /* not present is not an error */ }
    }
    return false;
}

/**
 * Can the user type `jarvis`?
 *
 * A match inside `node_modules/.bin` does NOT count. That directory is on PATH
 * only inside `npm run`, so trusting it would report success for a command that
 * does not exist in the user's actual terminal — which is the entire feature.
 */
async function commandAvailable() {
    const platform = detect.platform().os;
    const found = await detect.which('jarvis');

    if (found && !isLocalBinShim(found)) {
        return { available: true, path: found, source: 'path', needsNewShell: false };
    }

    const shim = commandPath(platform);
    if (!fs.existsSync(shim)) {
        return { available: false, path: null, source: null, needsNewShell: false };
    }

    const registered = await dirIsRegistered(commandDir(platform), platform);
    return registered
        ? { available: true, path: shim, source: 'registered', needsNewShell: !found }
        : { available: false, path: shim, source: 'unregistered', needsNewShell: false };
}

function isLocalBinShim(p) {
    return new RegExp(`node_modules[\\\\/]\\.bin[\\\\/]`).test(p);
}

// ── the operation ───────────────────────────────────────────────────────────

/**
 * Make `jarvis` work in a terminal, and verify that it will.
 *
 * @param {object} o
 * @param {string} o.root the install directory (where bin/ and package.json are)
 * @param {string|null} [o.packagedExe] set when called from the packaged app
 * @param {boolean} [o.dryRun] plan only
 * @returns {Promise<{status:'present'|'installed'|'manual'|'failed', detail?:string,
 *   dir?:string, command?:string, target?:string, needsNewShell?:boolean}>}
 */
async function ensureCommand({ root, packagedExe = null, dryRun = false, onLine } = {}) {
    const platform = detect.platform().os;
    const dir = commandDir(platform);
    const shim = path.join(dir, commandName(platform));

    // Someone else already owns the name. `npm i -g @ashutosh0x/jarvis` puts a
    // working shim in npm's global bin, and adding a second one would leave two
    // launchers whose PATH order decides which install answers.
    const existing = await detect.which('jarvis');
    if (existing && !isLocalBinShim(existing) && !samePathEntry(existing, shim, platform)) {
        return {
            status: 'present',
            detail: existing,
            command: existing,
            dir: path.dirname(existing),
            source: 'existing',
            needsNewShell: false,
        };
    }

    const launcher = resolveLauncher({ root, packagedExe, platform });

    // A 'cli' shim runs `node`. If the machine has no node, the shim would be a
    // command that exists and fails — worse than not being there.
    if (launcher.kind === 'cli') {
        if (!fs.existsSync(launcher.args[0])) {
            return {
                status: 'manual',
                detail: `The CLI entry point is missing (${launcher.args[0]}).`,
            };
        }
        if (launcher.cmd === 'node' && !(await detect.which('node'))) {
            return {
                status: 'manual',
                detail: 'Node is not on PATH, so a `jarvis` command could not run. '
                    + 'Install Node 22+ from https://nodejs.org, then run `jarvis link`.',
            };
        }
    }

    const contents = shimContents({
        platform, cmd: launcher.cmd, args: launcher.args, detach: launcher.detach,
    });

    if (dryRun) {
        return { status: 'dry-run', dir, command: shim, target: launcher.cmd, contents };
    }

    try {
        await fsp.mkdir(dir, { recursive: true });
        // Only write when the bytes differ, so a launch that changes nothing
        // does not touch the file's mtime.
        let current = null;
        try { current = await fsp.readFile(shim, 'utf-8'); } catch { /* absent */ }
        if (current !== contents) {
            await fsp.writeFile(shim, contents, 'utf-8');
            onLine?.(`Wrote ${shim}`);
        }
        if (platform !== 'windows') await fsp.chmod(shim, 0o755);
    } catch (e) {
        return { status: 'failed', detail: `Could not write the launcher: ${e.message}` };
    }

    // ── register the directory ──────────────────────────────────────────────
    let changed = false;
    try {
        if (platform === 'windows') {
            const backup = path.join(dir, 'path-backup.txt');
            const res = await addToWindowsPath(dir, backup);
            if (!res.ok) {
                return {
                    status: 'manual',
                    dir, command: shim,
                    detail: `The launcher is at ${shim} but PATH could not be updated `
                        + `(${res.detail}). Add that folder to PATH manually.`,
                };
            }
            changed = res.changed;
        } else {
            changed = await addToUnixPath(dir, onLine);
        }
    } catch (e) {
        return {
            status: 'manual',
            dir, command: shim,
            detail: `The launcher is at ${shim} but PATH could not be updated (${e.message}).`,
        };
    }

    // ── verify, rather than assume ──────────────────────────────────────────
    const registered = await dirIsRegistered(dir, platform);
    if (!registered) {
        return {
            status: 'manual',
            dir, command: shim,
            detail: `The launcher is at ${shim}, but PATH does not show it yet. `
                + 'Add that folder to PATH manually, or run `jarvis link` again.',
        };
    }

    return {
        status: changed ? 'installed' : 'present',
        dir,
        command: shim,
        target: [launcher.cmd, ...launcher.args].join(' '),
        kind: launcher.kind,
        // True whenever this process's own PATH cannot see it — which is always,
        // right after a change. Callers print "open a new terminal".
        needsNewShell: !pathContains(process.env.PATH, dir, platform),
        detail: shim,
    };
}

/** Append the guarded block to whichever rc files exist. Returns whether anything changed. */
async function addToUnixPath(dir, onLine) {
    // Already on PATH for new shells — most distributions put ~/.local/bin
    // there by default, and an rc edit that changes nothing is still an edit to
    // someone's dotfile.
    if (pathContains(process.env.PATH, dir, 'linux')) return false;

    let changed = false;
    for (const file of rcCandidates()) {
        let text;
        try {
            text = await fsp.readFile(file, 'utf-8');
        } catch {
            continue;   // only files that already exist
        }
        if (rcHasBlock(text)) continue;
        await fsp.writeFile(file, text + rcBlock(dir), 'utf-8');
        onLine?.(`Updated ${file}`);
        changed = true;
    }

    // Nothing to edit at all: a machine with no shell rc still needs one entry
    // point, and ~/.profile is the one every POSIX login shell reads.
    if (!changed && !(await anyRcHasBlock())) {
        const profile = path.join(os.homedir(), '.profile');
        await fsp.writeFile(profile, rcBlock(dir), { flag: 'a' });
        onLine?.(`Created ${profile}`);
        changed = true;
    }
    return changed;
}

async function anyRcHasBlock() {
    for (const file of rcCandidates()) {
        try {
            if (rcHasBlock(await fsp.readFile(file, 'utf-8'))) return true;
        } catch { /* absent */ }
    }
    return false;
}

/** Undo it: remove the launcher, the PATH entry and the rc block. */
async function removeCommand() {
    const platform = detect.platform().os;
    const dir = commandDir(platform);
    const shim = path.join(dir, commandName(platform));
    const removed = [];

    try {
        if (fs.existsSync(shim)) { await fsp.unlink(shim); removed.push(shim); }
    } catch (e) {
        return { status: 'failed', detail: `Could not remove ${shim}: ${e.message}` };
    }

    if (platform === 'windows') {
        const res = await removeFromWindowsPath(dir);
        if (!res.ok) return { status: 'manual', detail: `PATH was not changed (${res.detail}).`, removed };
        if (res.changed) removed.push(`PATH entry ${dir}`);
    } else {
        for (const file of rcCandidates()) {
            try {
                const text = await fsp.readFile(file, 'utf-8');
                if (!rcHasBlock(text)) continue;
                await fsp.writeFile(file, rcWithoutBlock(text), 'utf-8');
                removed.push(`block in ${file}`);
            } catch { /* absent */ }
        }
    }

    return { status: 'removed', removed, detail: removed.join(', ') || 'nothing to remove' };
}

module.exports = {
    // pure
    commandDir, commandName, commandPath, resolveLauncher, shimContents,
    splitPath, samePathEntry, pathContains, pathWith, pathWithout,
    rcBlock, rcHasBlock, rcWithoutBlock, rcCandidates, isLocalBinShim,
    // effectful
    ensureCommand, removeCommand, commandAvailable, dirIsRegistered,
    persistedWindowsPath, addToWindowsPath, removeFromWindowsPath,
    RC_MARKER,
};
